export const SET_SEARCH_QUERY = 'SET_SEARCH_QUERY'
export const FETCH_IMAGES = 'FETCH_IMAGES'
export const FETCH_IMAGES_SUCCESS = 'FETCH_IMAGES_SUCCESS'
export const FETCH_IMAGES_ERROR = 'FETCH_IMAGES_ERROR'